export const contactConstants = {
  CREATE_CONTACT_REQUEST: 'CREATE_CONTACT_REQUEST',
  CREATE_CONTACT_SUCCESS: 'CREATE_CONTACT_SUCCESS',
  CREATE_CONTACT_FAILURE: 'CREATE_CONTACT_FAILURE',

  GET_CONTACT_REQUEST: 'GET_CONTACT_REQUEST',
  GET_CONTACT_SUCCESS: 'GET_CONTACT_SUCCESS',
  GET_CONTACT_FAILURE: 'GET_CONTACT_FAILURE',
};