export const emailConstants = {
  CREATE_EMAIL_REQUEST: 'CREATE_EMAIL_REQUEST',
  CREATE_EMAIL_SUCCESS: 'CREATE_EMAIL_SUCCESS',
  CREATE_EMAIL_FAILURE: 'CREATE_EMAIL_FAILURE',

  GET_EMAIL_REQUEST: 'GET_EMAIL_REQUEST',
  GET_EMAIL_SUCCESS: 'GET_EMAIL_SUCCESS',
  GET_EMAIL_FAILURE: 'GET_EMAIL_FAILURE',
};