export const profileConstants = {
  CREATE_PROFILE_REQUEST: 'CREATE_PROFILE_REQUEST',
  CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
  CREATE_PROFILE_FAILURE: 'CREATE_PROFILE_FAILURE',

  GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

  SET_PROFILE_NAME: 'SET_PROFILE_NAME',

  DELETE_PROFILE_REQUEST: 'DELETE_PROFILE_REQUEST',
  DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
  DELETE_PROFILE_FAILURE: 'DELETE_PROFILE_FAILURE',
};