export const settingsConstants = {
  GET_PROFILE_SETTINGS_REQUEST: 'GET_PROFILE_SETTINGS_REQUEST',
  GET_PROFILE_SETTINGS_SUCCESS: 'GET_PROFILE_SETTINGS_SUCCESS',
  GET_PROFILE_SETTINGS_FAILURE: 'GET_PROFILE_SETTINGS_FAILURE',

  GET_PROFILE_NUMBERS_REQUEST: 'GET_PROFILE_NUMBERS_REQUEST',
  GET_PROFILE_NUMBERS_SUCCESS: 'GET_PROFILE_NUMBERS_SUCCESS',
  GET_PROFILE_NUMBERS_FAILURE: 'GET_PROFILE_NUMBERS_FAILURE',
};